version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - ACCOUNT_ID=$(aws sts get-caller-identity --query "Account" --output text)
      - REPO_URI=$ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/brain-tasks-app
      - echo $REPO_URI
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $REPO_URI
  build:
    commands:
      - echo Build started on `date`
      - docker build -t brain-tasks-app .
      - docker tag brain-tasks-app:latest $REPO_URI:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - docker push $REPO_URI:latest
      - printf '[{"name":"brain-tasks-app","imageUri":"%s"}]' $REPO_URI:latest > imagedefinitions.json
artifacts:
  files: imagedefinitions.json

